services:
  coinapp:
    build: .
    container_name: coinapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=db
      - KEYCLOAK_ISSUER=http://localhost:8081/realms/coinapp
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/coinapp/protocol/openid-connect/certs
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:16
    container_name: coinapp-db
    environment:
      POSTGRES_DB: coinapp
      POSTGRES_USER: coinuser
      POSTGRES_PASSWORD: coinpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: coinapp-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    volumes:
      - ./keycloak/coinapp-realm.json:/opt/keycloak/data/import/coinapp-realm.json:ro
    ports:
      - "8081:8080"

volumes:
  pgdata:
