package st.consoleapp.persistence;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;

/**
 * JDBC-based implementation of ModificationRepository.
 * Stores command events generated by asynchronous processing.
 */
public class JdbcModificationRepository implements ModificationRepository {

    private final Connection connection;

    /**
     * Initializes repository and database schema.
     */
    public JdbcModificationRepository(String jdbcUrl) {
        try {
            this.connection = DriverManager.getConnection(jdbcUrl);
            initializeSchema();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot initialize database", e);
        }
    }

    /**
     * Creates database schema if it does not exist.
     */
    private void initializeSchema() throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE IF NOT EXISTS data_modification (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    command_id VARCHAR(100) NOT NULL,
                    user_id VARCHAR(100) NOT NULL,
                    created_at TIMESTAMP NOT NULL
                )
            """);
        }
    }

    /**
     * Persists a single modification event.
     */
    @Override
    public synchronized void saveModification(String commandId, String userId) {
        String sql = """
            INSERT INTO data_modification (command_id, user_id, created_at)
            VALUES (?, ?, ?)
        """;

        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, commandId);
            ps.setString(2, userId);
            ps.setTimestamp(3, Timestamp.from(Instant.now()));
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot save modification for commandId=" + commandId + ", user=" + userId, e);
        }
    }

    /**
     * Returns number of modifications per user.
     */
    @Override
    public synchronized Map<String, Integer> countModificationsPerUser() {
        Map<String, Integer> result = new HashMap<>();

        String sql = """
            SELECT user_id, COUNT(*) AS modification_count
            FROM data_modification
            GROUP BY user_id
            ORDER BY user_id
            """;

        try (PreparedStatement ps = connection.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                result.put(
                        rs.getString("user_id"),
                        rs.getInt("modification_count")
                );
            }

            return result;
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot count modifications per user", e);
        }
    }

    /**
     * Closes underlying database resources.
     */
    @Override
    public synchronized void close() {
        try {
            connection.close();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot close database connection", e);
        }
    }
}
