package st.consoleapp.persistence;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;

public class JdbcModificationRepository implements ModificationRepository {

    private final Connection connection;

    public JdbcModificationRepository(String jdbcUrl) {
        try {
            this.connection = DriverManager.getConnection(jdbcUrl);
            initializeSchema();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot initialize database", e);
        }
    }

    private void initializeSchema() throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE IF NOT EXISTS data_modification (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    command_id VARCHAR(100) NOT NULL,
                    user_id VARCHAR(100) NOT NULL,
                    created_at TIMESTAMP NOT NULL
                )
            """);
        }
    }

    @Override
    public synchronized void saveModification(String commandId, String userId) {
        String sql = """
            INSERT INTO data_modification (command_id, user_id, created_at)
            VALUES (?, ?, ?)
        """;

        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, commandId);
            ps.setString(2, userId);
            ps.setTimestamp(3, Timestamp.from(Instant.now()));
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException(
                    "Cannot save modification for commandId=" + commandId + ", user=" + userId,
                    e
            );
        }
    }

    @Override

    public Map<String, Integer> countModificationsPerUser() {
        Map<String, Integer> result = new HashMap<>();
        try (PreparedStatement ps = connection.prepareStatement(
                "SELECT user_id, COUNT(*) FROM modifications GROUP BY user_id"
        )) {
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                result.put(rs.getString(1), rs.getInt(2));
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return result;
    }

    @Override
    public synchronized void close() {
        try {
            connection.close();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot close database connection", e);
        }
    }
}
