package st.consoleapp.persistence;

import java.sql.*;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;

public class JdbcModificationRepository implements ModificationRepository {

    private final Connection connection;

    public JdbcModificationRepository(String jdbcUrl) {
        try {
            this.connection = DriverManager.getConnection(jdbcUrl);
            initializeSchema();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot initialize database", e);
        }
    }

    private void initializeSchema() throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS data_modification (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id VARCHAR(100) NOT NULL,
                        created_at TIMESTAMP NOT NULL
                    )
                    """);
        }
    }

    @Override
    public synchronized void saveModification(String userId) {
        String sql = """
                INSERT INTO data_modification (user_id, created_at)
                VALUES (?, ?)
                """;

        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, userId);
            ps.setTimestamp(2, Timestamp.from(Instant.now()));
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot save modification for user: " + userId, e);
        }
    }

    @Override
    public synchronized Map<String, Integer> countModificationsPerUser() {
        String sql = """
                SELECT user_id, COUNT(*) AS modification_count
                FROM data_modification
                GROUP BY user_id
                ORDER BY user_id
                """;

        Map<String, Integer> result = new LinkedHashMap<>();

        try (PreparedStatement ps = connection.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                result.put(
                        rs.getString("user_id"),
                        rs.getInt("modification_count")
                );
            }

            return result;
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot count modifications", e);
        }
    }

    @Override
    public synchronized void close() {
        try {
            connection.close();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot close database connection", e);
        }
    }
}
