spring:
  application:
    name: coinapp

  profiles:
    default: localdev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/coinapp
    username: ${DB_USER:coinuser}
    password: ${DB_PASSWORD:coinpass}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        envers:
          do_not_audit_optimistic_locking_field: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8081/realms/coinapp}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/coinapp/protocol/openid-connect/certs}

server:
  servlet:
    context-path: /coinapp

management:
  endpoints:
    web:
      exposure:
        include: health