spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/coinapp
    username: coinuser
    password: coinpass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8081/realms/coinapp}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/coinapp/protocol/openid-connect/certs}

logging:
  level:
    org.springframework.boot.context.config: DEBUG

management:
  endpoint:
    health:
      show-details: always